{{ range $k, $v := .Values.services }}
{{ with $v }}
{{ if .route }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  {{- with .route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ $k }}
  namespace: argo-cd
  labels: &labels
    app.kubernetes.io/name: {{ $k }}
    app.kubernetes.io/instance: {{ $k }}-{{ $.Release.Name }}
    app.kubernetes.io/version: {{ $.Chart.Version }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  host: {{ .route.host }}
  to:
    kind: Service
    name: {{ $k }}
    weight: 100
  port:
    targetPort: {{ ($.service).port | default 80 }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
{{- end }}
{{- end }}
